### ISSUE TITLE
Support an admin user input for entering exercise information to the database

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#13]
As a application admin, i need to enter/modify exercises and add sports to database so users can take advantage of the most current information regarding the correct exercises for any particular sport.

Tasks

-[ ] Create an role based login for admin where the UI screen allows the admin to view, modify and delete exercises for a particular sport
-[ ] Create python function to connect to sqlite database and run insert, update, and query statements to fetch existing, modify existing and create new information for exercises for admin

**Days to complete: 3**

**Comment by andrw0** [comment]
@shankarchandru @urgreatman , the Django built in admin system should be working now. The admin can mange the users
