### ISSUE TITLE
Implement Python code to connect to a sqlite database and establish a database connection

### ISSUE THREAD

**Issue by shankarchandru** [shankarchandru/GameFitness#9]
The work is to implement python code to connect to database

As a developer, create python functions  to connect to Sqlite database and fetch all rows for users table

Tasks:

- [x] Create a python script which has a function to create a connection to sqlite db

- [x] Create a python function to fetch all rows from a valid sqlite database connection

**Days to complete: 1**

**Comment by andrw0** [comment]
@shankarchandru Thanks for finishing this up
